
---
### enabled rules
detectors:
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 50
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 30
  TooManyStatements:
    enabled: true
    exclude: []
    max_statements: 80
  TooManyConstants:
    enabled: true
    exclude: []
    max_constants: 50
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 8
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 8
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 5
    ignore_iterators:
    - tap
  ModuleInitialize:
    enabled: true
    exclude: []
  SubclassedFromCoreClass:
    enabled: true
    exclude: []

  ### unanabled rules
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: false
    exclude: []
  ClassVariable:
    enabled: false
    exclude: []
  ControlParameter:
    enabled: false
    exclude: []
  DataClump:
    enabled: false
    exclude: []
  DuplicateMethodCall:
    enabled: false
    exclude: []
  FeatureEnvy:
    enabled: false
    exclude: []
  InstanceVariableAssumption:
    enabled: false
    exclude: []
  IrresponsibleModule:
    enabled: false
    exclude: []
  ManualDispatch:
    enabled: false
    exclude: []
  NilCheck:
    enabled: false
    exclude: []
  RepeatedConditional:
    enabled: false
    exclude: []
  UncommunicativeMethodName:
    enabled: false
    exclude: []
  UncommunicativeModuleName:
    enabled: false
    exclude: []
  UncommunicativeParameterName:
    enabled: false
    exclude: []
  UncommunicativeVariableName:
    enabled: false
    exclude: []
  UnusedParameters:
    enabled: false
    exclude: []
  UtilityFunction:
    enabled: false
    exclude: []
