module Fusuma
  module Plugin
    module Detectors
      class PinchDetector < Detector
        # direction of gesture
        class Direction
          @target: untyped

          @base: untyped
        end

        # quantity of gesture
        class Quantity
          @target: untyped

          @base: untyped
        end
        @threshold: untyped
      end
    end
  end
end
