module Fusuma
  module Plugin
    module Detectors
      class RotateDetector < Detector
        # direction of gesture
        class Direction
          @angle: untyped
        end

        # quantity of gesture
        class Quantity
          @angle: untyped
        end
      end
    end
  end
end
