module Fusuma
  # Execute libinput command
  class LibinputCommand
    @libinput_command: untyped

    @debug_events_command: untyped

    @list_devices_command: untyped

    @libinput_options: untyped

    # version_command prints "1.6.3\n"
    @version: untyped

    @logged_list_devices: untyped
  end
end
