#!/usr/bin/env ruby

require 'optparse'
require_relative '../lib/fusuma'

option = {}
OptionParser.new do |opt|
  opt.on('-c',
         '--config=path/to/file',
         'Use an alternative config file') do |config_path|
    option[:config_path] = config_path
  end

  opt.on('-d',
         '--daemon',
         'Daemonize process') do |daemon|
    option[:daemon] = daemon
  end

  opt.on('-v',
         '--verbose',
         'Show details about the results of running fusuma') do |verbose|
    option[:verbose] = verbose
  end

  opt.on('--version',
         'Show fusuma version') do |version|
    option[:version] = version
  end

  opt.parse!(ARGV)
end

Fusuma::Runner.run(option)
